///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AzureDemoDesktop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AzureDemoDesktopRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("71defd03-7d50-4768-907d-e2766ded8342")]
    public partial class AzureDemoDesktopRepository : RepoGenBaseFolder
    {
        static AzureDemoDesktopRepository instance = new AzureDemoDesktopRepository();
        AzureDemoDesktopRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        AzureDemoDesktopRepositoryFolders.DepartmentListAppFolder _departmentlist;

        /// <summary>
        /// Gets the singleton class instance representing the AzureDemoDesktopRepository element repository.
        /// </summary>
        [RepositoryFolder("71defd03-7d50-4768-907d-e2766ded8342")]
        public static AzureDemoDesktopRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AzureDemoDesktopRepository() 
            : base("AzureDemoDesktopRepository", "/", null, 0, false, "71defd03-7d50-4768-907d-e2766ded8342", ".\\RepositoryImages\\AzureDemoDesktopRepository71defd03.rximgres")
        {
            _rxmainframe = new AzureDemoDesktopRepositoryFolders.RxMainFrameAppFolder(this);
            _departmentlist = new AzureDemoDesktopRepositoryFolders.DepartmentListAppFolder(this);
        }

#region Variables

        string _Genero = "Male";

        /// <summary>
        /// Gets or sets the value of variable Genero.
        /// </summary>
        [TestVariable("330f9622-bf5f-44bd-bc86-376bd74a4b51")]
        public string Genero
        {
            get { return _Genero; }
            set { _Genero = value; }
        }

        string _Departamento = "Sales";

        /// <summary>
        /// Gets or sets the value of variable Departamento.
        /// </summary>
        [TestVariable("756fc553-c8d0-4aa1-a9e2-b31605f415f7")]
        public string Departamento
        {
            get { return _Departamento; }
            set { _Departamento = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("71defd03-7d50-4768-907d-e2766ded8342")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("13ac802b-8aa6-48cc-85c8-6f49c2f676f9")]
        public virtual AzureDemoDesktopRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The DepartmentList folder.
        /// </summary>
        [RepositoryFolder("fef51697-47f1-4307-a397-843ba3947a05")]
        public virtual AzureDemoDesktopRepositoryFolders.DepartmentListAppFolder DepartmentList
        {
            get { return _departmentlist; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AzureDemoDesktopRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("13ac802b-8aa6-48cc-85c8-6f49c2f676f9")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            AzureDemoDesktopRepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;
            AzureDemoDesktopRepositoryFolders.RxTabStandardFolder _rxtabstandard;
            RepoItemInfo _introductionInfo;
            RepoItemInfo _testdatabaseInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "13ac802b-8aa6-48cc-85c8-6f49c2f676f9", "")
            {
                _rxtabintroduction = new AzureDemoDesktopRepositoryFolders.RxTabIntroductionFolder(this);
                _rxtabstandard = new AzureDemoDesktopRepositoryFolders.RxTabStandardFolder(this);
                _introductionInfo = new RepoItemInfo(this, "Introduction", "?/?/tabpage[@accessiblename='Introduction']", 30000, null, "681270cb-48bd-4c41-a0a4-c20b241d64ac");
                _testdatabaseInfo = new RepoItemInfo(this, "TestDatabase", "?/?/tabpage[@accessiblename='Test database']", 30000, null, "936964dc-3587-426d-b862-0c56c2e5fe31");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("13ac802b-8aa6-48cc-85c8-6f49c2f676f9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("13ac802b-8aa6-48cc-85c8-6f49c2f676f9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Introduction item.
            /// </summary>
            [RepositoryItem("681270cb-48bd-4c41-a0a4-c20b241d64ac")]
            public virtual Ranorex.TabPage Introduction
            {
                get
                {
                    return _introductionInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Introduction item info.
            /// </summary>
            [RepositoryItemInfo("681270cb-48bd-4c41-a0a4-c20b241d64ac")]
            public virtual RepoItemInfo IntroductionInfo
            {
                get
                {
                    return _introductionInfo;
                }
            }

            /// <summary>
            /// The TestDatabase item.
            /// </summary>
            [RepositoryItem("936964dc-3587-426d-b862-0c56c2e5fe31")]
            public virtual Ranorex.TabPage TestDatabase
            {
                get
                {
                    return _testdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabase item info.
            /// </summary>
            [RepositoryItemInfo("936964dc-3587-426d-b862-0c56c2e5fe31")]
            public virtual RepoItemInfo TestDatabaseInfo
            {
                get
                {
                    return _testdatabaseInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("03ad999c-2e00-4217-a524-aefdd284b260")]
            public virtual AzureDemoDesktopRepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }

            /// <summary>
            /// The RxTabStandard folder.
            /// </summary>
            [RepositoryFolder("f768d14f-2318-4153-98f3-54a37ee1bb56")]
            public virtual AzureDemoDesktopRepositoryFolders.RxTabStandardFolder RxTabStandard
            {
                get { return _rxtabstandard; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("03ad999c-2e00-4217-a524-aefdd284b260")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _resetInfo;
            RepoItemInfo _lblwelcomemessageInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "03ad999c-2e00-4217-a524-aefdd284b260", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/text[@accessiblename='Enter your name']", 30000, null, "2009b281-5ea5-42b7-9f3a-37745b4e468a");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "button[@controlname='btnSubmitUserName']", 30000, null, "61721661-e15c-48b7-9fe3-fbd7b0887d19");
                _resetInfo = new RepoItemInfo(this, "Reset", "link[@controlname='RxLinkBtnReset']/?/?/link[@accessiblename='Reset']", 30000, null, "da7c0744-e421-4a13-9aa8-193ed6adb5fa");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "text[@controlname='lblWelcomeMessage']", 30000, null, "91b00044-43ee-4869-b949-34a5fbbb69d9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("03ad999c-2e00-4217-a524-aefdd284b260")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("03ad999c-2e00-4217-a524-aefdd284b260")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("2009b281-5ea5-42b7-9f3a-37745b4e468a")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("2009b281-5ea5-42b7-9f3a-37745b4e468a")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("61721661-e15c-48b7-9fe3-fbd7b0887d19")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("61721661-e15c-48b7-9fe3-fbd7b0887d19")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The Reset item.
            /// </summary>
            [RepositoryItem("da7c0744-e421-4a13-9aa8-193ed6adb5fa")]
            public virtual Ranorex.Link Reset
            {
                get
                {
                    return _resetInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The Reset item info.
            /// </summary>
            [RepositoryItemInfo("da7c0744-e421-4a13-9aa8-193ed6adb5fa")]
            public virtual RepoItemInfo ResetInfo
            {
                get
                {
                    return _resetInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("91b00044-43ee-4869-b949-34a5fbbb69d9")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("91b00044-43ee-4869-b949-34a5fbbb69d9")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabStandardFolder folder.
        /// </summary>
        [RepositoryFolder("f768d14f-2318-4153-98f3-54a37ee1bb56")]
        public partial class RxTabStandardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _abrirInfo;
            RepoItemInfo _rdbmaleInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _updowneditInfo;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _itemsagregadosInfo;
            RepoItemInfo _listaagregadosInfo;
            RepoItemInfo _lblnumberofpersonsnumberInfo;

            /// <summary>
            /// Creates a new RxTabStandard  folder.
            /// </summary>
            public RxTabStandardFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabStandard", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "f768d14f-2318-4153-98f3-54a37ee1bb56", "")
            {
                _abrirInfo = new RepoItemInfo(this, "Abrir", "?/?/button[@accessiblename='Abrir']", 30000, null, "8719a526-1db6-4c04-a842-bc7767b043d5");
                _rdbmaleInfo = new RepoItemInfo(this, "RdbMale", "?/?/radiobutton[@controltext=$Genero]", 30000, null, "53481ca3-6587-462f-b2fc-df1e887315e4");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", 30000, null, "7b1ed7ae-7253-4d9d-95c2-7a8205d0cf28");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", 30000, null, "47577672-ae1b-4b5c-8b28-21da45f79d0d");
                _updowneditInfo = new RepoItemInfo(this, "UpDownEdit", "?/?/text[@controlname='upDownEdit']", 30000, null, "1c6829a8-3161-4784-9d8a-6cce65cba399");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", "button[@controlname='btnAddPerson']", 30000, null, "0a3a0090-4d17-437c-993d-1b45ef997544");
                _itemsagregadosInfo = new RepoItemInfo(this, "itemsAgregados", "list[@controlname='lstPersonList']/?/?/listitem[@accessiblename>'Fernando Figliola (male, 42)']", 30000, null, "d98525ab-c993-4fb2-ac87-0313a693fde8");
                _listaagregadosInfo = new RepoItemInfo(this, "listaAgregados", "list[@controlname='lstPersonList']/list", 30000, null, "a1e2f875-bac5-4f89-91f3-c4dbea3916e3");
                _lblnumberofpersonsnumberInfo = new RepoItemInfo(this, "LblNumberOfPersonsNumber", "text[@controlname='lblNumberOfPersonsNumber']", 30000, null, "2aa03e14-bd98-4d25-a919-d971ded89c08");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f768d14f-2318-4153-98f3-54a37ee1bb56")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f768d14f-2318-4153-98f3-54a37ee1bb56")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Abrir item.
            /// </summary>
            [RepositoryItem("8719a526-1db6-4c04-a842-bc7767b043d5")]
            public virtual Ranorex.Button Abrir
            {
                get
                {
                    return _abrirInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Abrir item info.
            /// </summary>
            [RepositoryItemInfo("8719a526-1db6-4c04-a842-bc7767b043d5")]
            public virtual RepoItemInfo AbrirInfo
            {
                get
                {
                    return _abrirInfo;
                }
            }

            /// <summary>
            /// The RdbMale item.
            /// </summary>
            [RepositoryItem("53481ca3-6587-462f-b2fc-df1e887315e4")]
            public virtual Ranorex.RadioButton RdbMale
            {
                get
                {
                    return _rdbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbMale item info.
            /// </summary>
            [RepositoryItemInfo("53481ca3-6587-462f-b2fc-df1e887315e4")]
            public virtual RepoItemInfo RdbMaleInfo
            {
                get
                {
                    return _rdbmaleInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("7b1ed7ae-7253-4d9d-95c2-7a8205d0cf28")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("7b1ed7ae-7253-4d9d-95c2-7a8205d0cf28")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("47577672-ae1b-4b5c-8b28-21da45f79d0d")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("47577672-ae1b-4b5c-8b28-21da45f79d0d")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The UpDownEdit item.
            /// </summary>
            [RepositoryItem("1c6829a8-3161-4784-9d8a-6cce65cba399")]
            public virtual Ranorex.Text UpDownEdit
            {
                get
                {
                    return _updowneditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UpDownEdit item info.
            /// </summary>
            [RepositoryItemInfo("1c6829a8-3161-4784-9d8a-6cce65cba399")]
            public virtual RepoItemInfo UpDownEditInfo
            {
                get
                {
                    return _updowneditInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("0a3a0090-4d17-437c-993d-1b45ef997544")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("0a3a0090-4d17-437c-993d-1b45ef997544")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The itemsAgregados item.
            /// </summary>
            [RepositoryItem("d98525ab-c993-4fb2-ac87-0313a693fde8")]
            public virtual Ranorex.ListItem itemsAgregados
            {
                get
                {
                    return _itemsagregadosInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The itemsAgregados item info.
            /// </summary>
            [RepositoryItemInfo("d98525ab-c993-4fb2-ac87-0313a693fde8")]
            public virtual RepoItemInfo itemsAgregadosInfo
            {
                get
                {
                    return _itemsagregadosInfo;
                }
            }

            /// <summary>
            /// The listaAgregados item.
            /// </summary>
            [RepositoryItem("a1e2f875-bac5-4f89-91f3-c4dbea3916e3")]
            public virtual Ranorex.List listaAgregados
            {
                get
                {
                    return _listaagregadosInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The listaAgregados item info.
            /// </summary>
            [RepositoryItemInfo("a1e2f875-bac5-4f89-91f3-c4dbea3916e3")]
            public virtual RepoItemInfo listaAgregadosInfo
            {
                get
                {
                    return _listaagregadosInfo;
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item.
            /// </summary>
            [RepositoryItem("2aa03e14-bd98-4d25-a919-d971ded89c08")]
            public virtual Ranorex.Text LblNumberOfPersonsNumber
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item info.
            /// </summary>
            [RepositoryItemInfo("2aa03e14-bd98-4d25-a919-d971ded89c08")]
            public virtual RepoItemInfo LblNumberOfPersonsNumberInfo
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo;
                }
            }
        }

        /// <summary>
        /// The DepartmentListAppFolder folder.
        /// </summary>
        [RepositoryFolder("fef51697-47f1-4307-a397-843ba3947a05")]
        public partial class DepartmentListAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _itemdepartamentoInfo;

            /// <summary>
            /// Creates a new DepartmentList  folder.
            /// </summary>
            public DepartmentListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DepartmentList", "/list[@controlid='1000']", parentFolder, 30000, null, true, "fef51697-47f1-4307-a397-843ba3947a05", "")
            {
                _itemdepartamentoInfo = new RepoItemInfo(this, "itemDepartamento", "listitem[@text=$Departamento]", 30000, null, "bdc469a7-6e3c-4b59-b150-2b1551ddf472");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fef51697-47f1-4307-a397-843ba3947a05")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fef51697-47f1-4307-a397-843ba3947a05")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The itemDepartamento item.
            /// </summary>
            [RepositoryItem("bdc469a7-6e3c-4b59-b150-2b1551ddf472")]
            public virtual Ranorex.ListItem itemDepartamento
            {
                get
                {
                    return _itemdepartamentoInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The itemDepartamento item info.
            /// </summary>
            [RepositoryItemInfo("bdc469a7-6e3c-4b59-b150-2b1551ddf472")]
            public virtual RepoItemInfo itemDepartamentoInfo
            {
                get
                {
                    return _itemdepartamentoInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
