///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AzureDemoDesktop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AzureDemoDesktopRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("71defd03-7d50-4768-907d-e2766ded8342")]
    public partial class AzureDemoDesktopRepository : RepoGenBaseFolder
    {
        static AzureDemoDesktopRepository instance = new AzureDemoDesktopRepository();
        AzureDemoDesktopRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the AzureDemoDesktopRepository element repository.
        /// </summary>
        [RepositoryFolder("71defd03-7d50-4768-907d-e2766ded8342")]
        public static AzureDemoDesktopRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AzureDemoDesktopRepository() 
            : base("AzureDemoDesktopRepository", "/", null, 0, false, "71defd03-7d50-4768-907d-e2766ded8342", ".\\RepositoryImages\\AzureDemoDesktopRepository71defd03.rximgres")
        {
            _rxmainframe = new AzureDemoDesktopRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("71defd03-7d50-4768-907d-e2766ded8342")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("13ac802b-8aa6-48cc-85c8-6f49c2f676f9")]
        public virtual AzureDemoDesktopRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AzureDemoDesktopRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("13ac802b-8aa6-48cc-85c8-6f49c2f676f9")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            AzureDemoDesktopRepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;
            RepoItemInfo _introductionInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "13ac802b-8aa6-48cc-85c8-6f49c2f676f9", "")
            {
                _rxtabintroduction = new AzureDemoDesktopRepositoryFolders.RxTabIntroductionFolder(this);
                _introductionInfo = new RepoItemInfo(this, "Introduction", "?/?/tabpage[@accessiblename='Introduction']", 30000, null, "681270cb-48bd-4c41-a0a4-c20b241d64ac");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("13ac802b-8aa6-48cc-85c8-6f49c2f676f9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("13ac802b-8aa6-48cc-85c8-6f49c2f676f9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Introduction item.
            /// </summary>
            [RepositoryItem("681270cb-48bd-4c41-a0a4-c20b241d64ac")]
            public virtual Ranorex.TabPage Introduction
            {
                get
                {
                    return _introductionInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Introduction item info.
            /// </summary>
            [RepositoryItemInfo("681270cb-48bd-4c41-a0a4-c20b241d64ac")]
            public virtual RepoItemInfo IntroductionInfo
            {
                get
                {
                    return _introductionInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("03ad999c-2e00-4217-a524-aefdd284b260")]
            public virtual AzureDemoDesktopRepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("03ad999c-2e00-4217-a524-aefdd284b260")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _resetInfo;
            RepoItemInfo _lblwelcomemessageInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "03ad999c-2e00-4217-a524-aefdd284b260", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/text[@accessiblename='Enter your name']", 30000, null, "2009b281-5ea5-42b7-9f3a-37745b4e468a");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "button[@controlname='btnSubmitUserName']", 30000, null, "61721661-e15c-48b7-9fe3-fbd7b0887d19");
                _resetInfo = new RepoItemInfo(this, "Reset", "link[@controlname='RxLinkBtnReset']/?/?/link[@accessiblename='Reset']", 30000, null, "da7c0744-e421-4a13-9aa8-193ed6adb5fa");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "text[@controlname='lblWelcomeMessage']", 30000, null, "91b00044-43ee-4869-b949-34a5fbbb69d9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("03ad999c-2e00-4217-a524-aefdd284b260")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("03ad999c-2e00-4217-a524-aefdd284b260")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("2009b281-5ea5-42b7-9f3a-37745b4e468a")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("2009b281-5ea5-42b7-9f3a-37745b4e468a")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("61721661-e15c-48b7-9fe3-fbd7b0887d19")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("61721661-e15c-48b7-9fe3-fbd7b0887d19")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The Reset item.
            /// </summary>
            [RepositoryItem("da7c0744-e421-4a13-9aa8-193ed6adb5fa")]
            public virtual Ranorex.Link Reset
            {
                get
                {
                    return _resetInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The Reset item info.
            /// </summary>
            [RepositoryItemInfo("da7c0744-e421-4a13-9aa8-193ed6adb5fa")]
            public virtual RepoItemInfo ResetInfo
            {
                get
                {
                    return _resetInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("91b00044-43ee-4869-b949-34a5fbbb69d9")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("91b00044-43ee-4869-b949-34a5fbbb69d9")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
